name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: therayquaza/epita-mlops-mateo-tp1:latest

      - 
        name: Deploy Docker container to remote server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            docker kill $(docker ps -q --filter ancestor=therayquaza/epita-mlops-mateo-tp1:latest) || true
            docker run -d --rm -p 5678:5678 -e PORT=5678 -e HOST=0.0.0.0 --name epita-mlops-mateo-tp1 therayquaza/epita-mlops-mateo-tp1:latest
